export const TACTICS_MOVE_UNIT_ACTION = 'tactics:move_unit';
export const TACTICS_ATTACK_ACTION = 'tactics:attack';
export const TACTICS_REVEAL_TILE_ACTION = 'tactics:reveal_tile';
export const TACTICS_DEFAULT_UNIT_ID_VALUE = 'unit-1';
export const TACTICS_PROXIMITY_REVEAL_RANGE_TILES = 1;
export const TACTICS_PROXIMITY_REVEAL_RANGE_TILES_SQUARED =
    TACTICS_PROXIMITY_REVEAL_RANGE_TILES * TACTICS_PROXIMITY_REVEAL_RANGE_TILES;
export const TACTICS_INITIAL_UNIT_SPACING_TILES = TACTICS_PROXIMITY_REVEAL_RANGE_TILES + 1;
