// AUTO-GENERATED by tools/gen-toolchain.ts — DO NOT EDIT BY HAND.
//
// Regenerate with `pnpm gen:toolchain`; `pnpm verify:toolchain-snapshot` fails if this drifts
// from the live root package.json toolchain, the engine package versions, or the root tsconfig.
//
// Frozen so the published create-chimera-game CLI can emit a standalone project with the exact
// toolchain + engine versions the monorepo builds against, without reading the monorepo at
// `npm create` time. This file is prettier/eslint-ignored: it is a machine artifact.

/** Root devDependencies + dependencies, minus every `@chimera-engine/*` workspace edge. */
export const TOOLCHAIN_DEPS: Readonly<Record<string, string>> = {
    "@changesets/cli": "^2.31.0",
    "@eslint/css": "^1.2.0",
    "@eslint/js": "^9.39.4",
    "@next/eslint-plugin-next": "^16.2.6",
    "@playwright/test": "^1.59.1",
    "@react-three/fiber": "^9.6.1",
    "@react-three/test-renderer": "^9.1.0",
    "@testing-library/jest-dom": "^6.9.1",
    "@testing-library/react": "^16.3.2",
    "@testing-library/user-event": "^14.6.1",
    "@types/node": "^22.10.0",
    "@types/pino": "^7.0.5",
    "@types/pngjs": "^6.0.5",
    "@types/react": "^19.2.14",
    "@types/react-dom": "^19.2.3",
    "@types/three": "^0.184.1",
    "@types/ws": "^8.18.1",
    "@vitest/browser": "^4.1.5",
    "@vitest/coverage-v8": "^3.2.4",
    "chokidar": "^5.0.0",
    "cross-env": "^10.1.0",
    "electron": "^33.2.0",
    "esbuild": "^0.28.0",
    "eslint": "^9.39.4",
    "eslint-config-prettier": "^9.1.2",
    "fast-check": "^4.7.0",
    "jsdom": "^29.0.2",
    "next": "^15.5.15",
    "pino": "^10.3.1",
    "pngjs": "^7.0.0",
    "prettier": "^3.3.3",
    "publint": "^0.3.21",
    "react": "^19.2.5",
    "react-dom": "^19.2.5",
    "three": "^0.184.0",
    "tsx": "^4.21.0",
    "typescript": "^5.7.2",
    "typescript-eslint": "^8.59.0",
    "vite-tsconfig-paths": "^4.3.2",
    "vitest": "^3.2.4",
    "ws": "^8.20.0",
    "zod": "^4.3.6",
    "zustand": "^5.0.12"
};

/** `^<version>` per publishable engine package, from each package's own version field. */
export const ENGINE_DEP_RANGES: Readonly<Record<string, string>> = {
    "@chimera-engine/ai": "^0.9.0",
    "@chimera-engine/electron": "^0.9.0",
    "@chimera-engine/networking": "^0.9.0",
    "@chimera-engine/renderer": "^0.9.0",
    "@chimera-engine/simulation": "^0.9.0"
};

/** The root tsconfig `compilerOptions`, frozen for the standalone app's inlined tsconfig. */
export const ROOT_COMPILER_OPTIONS = {
    "baseUrl": ".",
    "esModuleInterop": true,
    "exactOptionalPropertyTypes": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "lib": [
        "ES2022"
    ],
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ES2022",
    "types": [
        "node"
    ],
    "verbatimModuleSyntax": false
} as const;
